[project]
name = "py-wake-cli"
version = "2.0.6a0"
description = "A simple wakeonlan implementation."
authors = [{ name = "lojoja", email = "dev@lojoja.com" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = { text = "MIT" }
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "click==8.*",
  "clickext>=1.0.1,<2",
  "tabulate>=0.9,<1",
]

[dependency-groups]
dev = [
  "pytest>=9.0.2,<10",
  "pytest-cov>=4.1,<8.0",
  "pytest-mock>=3.15.1,<4",
  "ruff>=0.14.14",
  "ty>=0.0.14",
]

[project.urls]
homepage = "https://github.com/lojoja/wake"
repository = "https://github.com/lojoja/wake"
"Bug Tracker" = "https://github.com/lojoja/wake/issues"

[project.scripts]
wake = "wake.cli:cli"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[tool.coverage.run]
source = ["wake"]
omit = ["tests/"]
branch = true

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "if log:"
]
fail_under = 100
show_missing = true

[tool.pytest.ini_options]
addopts = "--strict-markers"
testpaths = ["tests"]
markers=[]
filterwarnings = ["ignore:::.*pytest_cov*"]

[tool.ruff]
line-length = 120
target-version = "py313"
src = ["src", "tests"]
extend-exclude = ["build"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM812", "D203", "D213", "E111", "E114", "E117"]
fixable = ["ALL"]
unfixable = []
mccabe.max-complexity = 10

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "FBT001",
  "INP001",
  "PLR0913",
  "S101"
]
"tests/test_wake.py" = [
    "SLF001"
]

[tool.ty]
src.include = ["src", "tests"]

[tool.uv.build-backend]
module-name = ["wake"]
