name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
    steps:
      - name: Download release assets
        uses: dsaltares/fetch-gh-release-asset@aa2ab1243d6e0d5b405b973c89fa4d06a2d0fff7
        with:
          version: ${{ github.event.release.id }}
          regex: true
          file: py_wake_cli-.+
          target: dist/
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish on TestPyPi
        uses: pypa/gh-action-pypi-publish@8a08d616893759ef8e1aa1f2785787c0b97e20d6
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/
      - name: Publish on PyPi
        uses: pypa/gh-action-pypi-publish@8a08d616893759ef8e1aa1f2785787c0b97e20d6
        with:
          packages-dir: dist/
