name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
    steps:
      - name: Download release assets
        uses: dsaltares/fetch-gh-release-asset@aa2ab1243d6e0d5b405b973c89fa4d06a2d0fff7
        with:
          version: ${{ github.event.release.id }}
          regex: true
          file: py_wake_cli-.+
          target: assets/
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish on TestPyPi
        uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: assets/
      - name: Publish on PyPi
        uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0
        with:
          packages-dir: assets/
