name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  style:
    name: Style
    uses: ./.github/workflows/style.yml
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    needs: [style, tests]
  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806
        with:
          name: dist
          path: dist/
      - name: Create release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          target_commitish: ${{ github.sha }}
          tag_name: ${{ needs.build.outputs.VERSION }}
          prerelease: ${{ needs.build.outputs.IS_PRERELEASE == 1 }}
          draft: true
          files: dist/*
          fail_on_unmatched_files: true
