name: Style

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_call:
  workflow_dispatch:

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.10"
    steps:
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install poetry
        run: pipx install poetry
      - name: Set up python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry
      - name: Install project
        run: poetry install
      - name: Run pylint
        run: poetry run pylint --recursive=y .
      - name: Run black
        run: poetry run black --check .
