name: Style

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Install poetry
        run: pipx install poetry
      - name: Set up python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install project
        run: poetry install
      - name: Run pylint
        run: poetry run pylint --recursive=y .
      - name: Run black
        run: poetry run black --check .
