name: Style

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install poetry
        run: pipx install poetry
      - name: Set up python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install project
        run: poetry install
      - name: Run pylint
        run: poetry run pylint --recursive=y .
      - name: Run black
        run: poetry run black --check .
